# Generated by Django 3.1.1 on 2020-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('smail', models.EmailField(max_length=100)),
                ('spass', models.CharField(max_length=20)),
                ('sdept', models.CharField(max_length=10)),
            ],
        ),
    ]
