# Generated by Django 3.1.1 on 2020-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('fname', models.CharField(max_length=30)),
                ('fmail', models.EmailField(max_length=100)),
                ('fpass', models.CharField(max_length=20)),
            ],
        ),
    ]
